### ISSUE TITLE
eval.py中的getNumber（s）s

### ISSUE THREAD

**Issue by wmy10128** [mrezaei92/TriHorn-Net#7]

**Comment by wmy10128** [comment]
import re
def getNumber(s):
    return int(re.findall('[0-9]+', s)[0])

Traceback (most recent call last):
  File "D:\download\TriHorn-Net-main\eval.py", line 131, in <module>
    list_files.sort(key=getNumber)
  File "D:\download\TriHorn-Net-main\eval.py", line 17, in getNumber
    return int(re.findall('[0-9]+', s)[0])
IndexError: list index out of range

Sorry to bother you, but what does the "s" in eval.py represent? Could you help me solve this problem?

**Comment by whutdhz** [comment]
I also have the same issue, do you solve it?
